# -*- coding: utf-8 -*-
"""Technical Lab Sheet  3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17lZAnHfvLQvaVtNwwi46iq4IBSwjFzP1

#### **Experiment No. 3**
#### **Experiment Name - Statistical Analysis and Hypothesis Testing using Python**

#### **Steps**

##### **NAME : Atul Krishna**
##### **COURSE : B.Tech CSE**
##### **SECTION - B**
##### **SUBJECT : Mastery in Data Analytics and Visualizations and Career Advancement**
##### **ROLL NO. : 14**
##### **CU ID : CU24250231**

#####**1. Select a real-world dataset such as the IBM HR Employee Attrition Dataset, Titanic Survival Dataset, or House Price Prediction Dataset.**
"""

# Selecting a Real-World Dataset

from google.colab import files
uploaded = files.upload()

import os
print(os.listdir())

dataset_name = "House Price Prediction Dataset"

print("Selected Dataset:", dataset_name)
print("Dataset selected successfully!")

"""#####**2. Import the required Python libraries including Pandas, NumPy, SciPy, Matplotlib, and Statsmodels.**"""

# Importing Required Python Libraries
import pandas as pd
import numpy as np
import scipy.stats as stats
import matplotlib.pyplot as plt
import statsmodels.api as sm
import seaborn as sns

print("All required libraries imported successfully!")

"""#####**3. Load the dataset and calculate descriptive statistics such as mean, median, mode, variance, and standard deviation for relevant numerical features.**"""

# Load the dataset
df = pd.read_csv("House Price Prediction Dataset.csv")

print("Dataset loaded successfully!")
print("Shape of dataset:", df.shape)

print("\nFirst 5 rows:")
print(df.head())

# Select numerical features
numerical_data = df.select_dtypes(include=np.number)

# Calculate descriptive statistics
descriptive_stats = pd.DataFrame({
    "Mean": numerical_data.mean(),
    "Median": numerical_data.median(),
    "Mode": numerical_data.mode().iloc[0],
    "Variance": numerical_data.var(),
    "Standard Deviation": numerical_data.std()
})

print("\nDescriptive Statistics:")
print(descriptive_stats.round(2))

"""#####**4. Analyze relationships between variables by calculating the Pearson correlation coefficient and visualizing the correlation matrix.**"""

# Calculate Pearson correlation coefficients
correlation_matrix = numerical_data.corr(method="pearson")

print("Pearson Correlation Matrix:")
print(correlation_matrix.round(3))

# Visualize the correlation matrix
plt.figure(figsize=(6, 5))
sns.heatmap(correlation_matrix, annot=True, cmap="coolwarm", fmt=".2f")
plt.title("Pearson Correlation Matrix")
plt.show()

"""The correlation between Area and Price in this dataset is approximately:

Area - Price = 0.002

This indicates an almost zero linear correlation between Area and Price in this particular dataset.

Interpretation: The Pearson correlation coefficient measures the strength and direction of the linear relationship between two numerical variables. In this dataset, the correlation between Area and Price is approximately 0.002, indicating that there is almost no linear relationship between these two variables.

#####**5. Formulate a Null Hypothesis (H₀) and an Alternative Hypothesis (H₁) for a business problem (e.g., "Is there a significant difference in monthly income between employees who leave the company and those who stay?").**

For the t-test, we will compare house prices based on whether a house has a garage.

**Business Problem**: Is there a significant difference in the average house price between houses with a garage and houses without a garage?

**Hypotheses**

**H₀ (Null Hypothesis)**: There is no significant difference in the mean house price between houses with a garage and houses without a garage.

**H₁ (Alternative Hypothesis)**: There is a significant difference in the mean house price between houses with a garage and houses without a garage.

**Significance level**: α = 0.05

#####**6. Perform an Independent Sample t-test to compare the means of two groups and interpret the p-value.**
"""

# Separate house prices based on Garage
garage_yes = df[df["Garage"] == "Yes"]["Price"]
garage_no = df[df["Garage"] == "No"]["Price"]

# Perform independent sample t-test
t_statistic, p_value = stats.ttest_ind(
    garage_yes,
    garage_no,
    equal_var=False
)

# Display results
print("Independent Sample t-Test:")
print("Mean Price - Garage Yes:", round(garage_yes.mean(), 2))
print("Mean Price - Garage No :", round(garage_no.mean(), 2))
print("t-statistic:", round(t_statistic, 4))
print("p-value:", round(p_value, 6))

# Interpret the p-value
alpha = 0.05

print("\nInterpretation:")
if p_value < alpha:
    print("Decision: Reject the Null Hypothesis (H₀)")
    print("Conclusion: There is a significant difference in house prices.")
else:
    print("Decision: Fail to Reject the Null Hypothesis (H₀)")
    print("Conclusion: There is no significant difference in house prices.")

"""Since: p-value = 0.898870 > 0.05

So, we fail to reject H₀.

Therefore, there is no statistically significant difference in average house prices between houses with garages and houses without garages in this dataset.

#####**7. Apply One-Way ANOVA to determine whether there is a statistically significant difference among multiple groups (e.g., employee satisfaction across different job roles).**
"""

# Create groups based on house condition
excellent = df[df["Condition"] == "Excellent"]["Price"]
good = df[df["Condition"] == "Good"]["Price"]
fair = df[df["Condition"] == "Fair"]["Price"]
poor = df[df["Condition"] == "Poor"]["Price"]

# Perform One-Way ANOVA
f_statistic, p_value_anova = stats.f_oneway(
    excellent,
    good,
    fair,
    poor
)

# Display results
print("One-Way ANOVA:")
print("F-statistic:", round(f_statistic, 4))
print("p-value:", round(p_value_anova, 6))

# Interpret the p-value
alpha = 0.05

print("\nInterpretation:")
if p_value_anova < alpha:
    print("Decision: Reject the Null Hypothesis (H₀)")
    print("Conclusion: There is a significant difference among the group means.")
else:
    print("Decision: Fail to Reject the Null Hypothesis (H₀)")
    print("Conclusion: There is no significant difference among the group means.")

"""Since: p-value = 0.182562 > 0.05

So, we fail to reject the null hypothesis.

Therefore, there is no statistically significant difference in average house prices among the different house condition groups in this dataset.

#####**8. Build a simple Linear Regression model to analyze the relationship between two numerical variables, such as Years of Experience and Monthly Income or House Area and House Price.**

We will analyze the relationship between:
* Independent Variable (X): Area
* Dependent Variable (Y): Price

**Regression Equation**
* The model will have the form: **Price = β₀ + β₁(Area)**
"""

# Define independent variable (X) and dependent variable (Y)
X = df[["Area"]]
y = df["Price"]

# Add constant for intercept
X = sm.add_constant(X)

# Build and fit the Linear Regression model
model = sm.OLS(y, X).fit()

print("Simple Linear Regression: Area vs Price:")
print(model.summary())

# Get regression values
intercept = model.params["const"]
slope = model.params["Area"]
r_squared = model.rsquared

print("\nRegression Equation:")
print(f"Price = {intercept:.2f} + ({slope:.4f} × Area)")

print("\nIntercept:", round(intercept, 2))
print("Area Coefficient:", round(slope, 4))
print("R² Score:", round(r_squared, 6))

print("Regression Coefficients:")
print(model.params)

print("\nR-squared:", model.rsquared)

print("\n95% Confidence Intervals:")
print(model.conf_int())

"""#####**9. Interpret the statistical outputs, including p-values, confidence intervals, regression coefficients, and R² score.**"""

# Interpreting Statistical Outputs
# Regression coefficients
intercept = model.params["const"]
slope = model.params["Area"]

# R-squared
r_squared = model.rsquared

# P-value of Area coefficient
p_value_area = model.pvalues["Area"]

# 95% Confidence Interval
confidence_interval = model.conf_int().loc["Area"]

print("========== STATISTICAL OUTPUT INTERPRETATION ==========")

print("\n1. Regression Coefficients:")
print("Intercept:", round(intercept, 2))
print("Area Coefficient:", round(slope, 4))

print("\n2. P-value:")
print("P-value for Area:", round(p_value_area, 6))

print("\n3. 95% Confidence Interval for Area:")
print("Lower Limit:", round(confidence_interval[0], 4))
print("Upper Limit:", round(confidence_interval[1], 4))

print("\n4. R² Score:")
print("R²:", round(r_squared, 6))

# Interpretation
print("\n========== INTERPRETATION ==========")

if p_value_area < 0.05:
    print("The p-value is less than 0.05, indicating that Area has a statistically significant relationship with House Price.")
else:
    print("The p-value is greater than 0.05, indicating that Area does not have a statistically significant linear relationship with House Price.")

print("\nThe regression coefficient of Area indicates the expected change in House Price for a one-unit increase in Area.")
print("\nThe 95% confidence interval gives the range of plausible values for the true regression coefficient of Area.")

if r_squared < 0.1:
    print("\nThe R² score is very close to zero, indicating that Area explains very little of the variation in House Price.")
else:
    print("\nThe R² score indicates the proportion of variation in House Price that is explained by Area.")

"""#####**10. Summarize the findings and discuss how statistical analysis can support business decisions and predictive analytics.**

**SUMMARY OF FINDINGS**: The House Price Prediction Dataset was analyzed using descriptive statistics, Pearson correlation, Independent Sample t-Test,
One-Way ANOVA, and Simple Linear Regression.

1. Descriptive statistics were used to calculate the mean, median,
   mode, variance, and standard deviation of the numerical variables.

2. Pearson correlation analysis was performed to identify relationships
   between numerical variables. The correlation between Area and Price
   was found to be very weak.

3. An Independent Sample t-Test was performed to compare the average
   house prices between houses with a garage and houses without a garage.
   The p-value was greater than 0.05, so the difference was not
   statistically significant.

4. One-Way ANOVA was performed to compare house prices among different
   house condition groups. The p-value was greater than 0.05, indicating
   that there was no statistically significant difference among the
   condition groups.

5. Simple Linear Regression was performed using Area as the independent
   variable and Price as the dependent variable. The R² score was very
   close to zero, indicating that Area alone does not explain much of
   the variation in House Price.

**BUSINESS APPLICATIONS**:

Statistical analysis helps organizations make data-driven decisions
instead of relying only on assumptions. It can be used to identify
important relationships, compare different groups, test business
hypotheses, and measure the significance of observed patterns.

In real-estate business, statistical analysis can help organizations
understand factors affecting house prices, evaluate property features,
identify market trends, and support pricing decisions.

Regression analysis can also be used as a foundation for predictive
analytics. By using multiple important features such as Area, Bedrooms,
Bathrooms, Location, YearBuilt, and other relevant variables, organizations
can develop better models for predicting house prices.

Therefore, statistical analysis is useful for understanding data,
validating assumptions, supporting business decisions, and building
reliable predictive analytics models.

####**Questions and Answers**

Q1. What is the difference between descriptive statistics and inferential statistics?

Answer: Descriptive statistics are used to summarize and describe the main characteristics of a dataset. They include measures such as mean, median, mode, variance, standard deviation, minimum, and maximum.

Inferential statistics are used to draw conclusions or make predictions about a larger population based on sample data. Hypothesis testing, t-tests, ANOVA, confidence intervals, and regression analysis are examples of inferential statistics.

In short:
* Descriptive statistics → Describe the available data.
* Inferential statistics → Draw conclusions beyond the available data.

Q2. Explain the concepts of the Null Hypothesis (H₀) and Alternative Hypothesis (H₁).

Answer: The **Null Hypothesis (H₀)** is a statement that assumes there is no significant difference, relationship, or effect between the variables being studied.

The **Alternative Hypothesis (H₁)** is the opposite of the null hypothesis. It states that a significant difference, relationship, or effect exists.

For example, in this experiment:

H₀: There is no significant difference in house prices between houses with garages and houses without garages.

H₁: There is a significant difference in house prices between houses with garages and houses without garages.

A statistical test is performed to determine whether there is enough evidence to reject H₀.

Q3. What is a p-value? How is it used to make statistical decisions?

Answer: A p-value represents the probability of obtaining the observed result, or a more extreme result, assuming that the null hypothesis is true.

A significance level of 0.05 is commonly used.
* If p-value < 0.05, reject H₀.
* If p-value ≥ 0.05, fail to reject H₀.

For example, the t-test in this experiment produced a p-value of approximately 0.898870. Since this value is greater than 0.05, the null hypothesis was not rejected.

Q4. Differentiate between a t-test and ANOVA. In which situations is each test applied?

Answer:

**T-test** is generally used to compare the means of two groups.

For example: Comparing the average house prices of houses with garages and houses without garages.

**ANOVA (Analysis of Variance)** is used to compare the means of three or more groups.

For example: Comparing the average house prices among Excellent, Good, Fair, and Poor condition houses.

| t-test                    | ANOVA                                      |
| ------------------------- | ------------------------------------------ |
| Compares two groups       | Compares three or more groups              |
| Produces a t-statistic    | Produces an F-statistic                    |
| Example: Garage Yes vs No | Example: Excellent vs Good vs Fair vs Poor |

Q5. What does the Pearson correlation coefficient indicate? What are its possible values?

Answer: The Pearson correlation coefficient measures the strength and direction of a linear relationship between two numerical variables.

Its values range from:
* -1 to +1

Interpretation:
* +1 → Perfect positive correlation
* 0 → No linear correlation
* -1 → Perfect negative correlation

A positive value indicates that both variables tend to increase together, while a negative value indicates that one variable tends to decrease when the other increases.

In this dataset, the correlation between Area and Price is approximately 0.002, indicating almost no linear relationship.

Q6. Explain the significance of R² (Coefficient of Determination) in Linear Regression.

Answer: **R², or the Coefficient of Determination**, indicates the proportion of variation in the dependent variable that can be explained by the independent variable or variables in a regression model.

Its value generally ranges from 0 to 1.
* R² = 0 → Model explains almost none of the variation.
* R² = 1 → Model explains all of the variation.

In this experiment, the R² value is approximately:
* 0.00000238

This is extremely close to zero, meaning that Area explains almost none of the variation in house Price in this dataset.

Q7. Why is statistical analysis important before applying machine learning algorithms?

Answer: Statistical analysis is important before applying machine learning because it helps understand the dataset and identify important patterns and relationships.

It helps to:
1. Understand the distribution of data.
2. Detect outliers and unusual values.
3. Identify relationships between variables.
4. Detect highly correlated features.
5. Validate assumptions.
6. Test whether observed relationships are statistically significant.
7. Select appropriate features.
8. Improve the quality of machine learning models.
9. Avoid misleading conclusions.
10. Support better data-driven decisions.

Therefore, statistical analysis provides a strong foundation for effective machine learning and predictive analytics.

Q8. What assumptions should be satisfied before performing a t-test or ANOVA?

Answer:

Assumptions of a t-test:
1. The observations should be independent.
2. The dependent variable should be numerical.
3. The data should be approximately normally distributed within each group, especially for small samples.
4. For the standard independent t-test, the variances of the two groups should be approximately equal. If this assumption is violated, Welch's t-test can be used.

Assumptions of ANOVA:
1. Observations should be independent.
2. The dependent variable should be numerical.
3. The data in each group should be approximately normally distributed.
4. The variances of the groups should be approximately equal.
5. The groups should be independent of one another.

Tests such as Shapiro-Wilk can be used to check normality, while Levene's test can be used to check equality of variances.

Q9. How can regression analysis help organizations in forecasting and decision-making?

Answer: Regression analysis helps organizations understand relationships between variables and make predictions about future outcomes.

For example, a real-estate company can use regression to estimate house prices based on factors such as:
* House area
* Number of bedrooms
* Number of bathrooms
* Location
* Year built

Regression analysis can help organizations with:
1. Forecasting future values.
2. Estimating prices and revenue.
3. Identifying important factors affecting an outcome.
4. Planning resources.
5. Supporting business decisions.
6. Understanding trends.
7. Predictive analytics.

Therefore, regression provides quantitative information that can help organizations make better data-driven decisions.

Q10. Give two real-world applications where hypothesis testing is commonly used in data analytics.

Answer:

1. **Marketing:** A company can use hypothesis testing to determine whether a new advertising campaign produces a significantly higher conversion rate than an existing campaign.
   * H₀: The new campaign does not improve conversion rate.
   * H₁: The new campaign improves conversion rate.

2. **Healthcare:** A healthcare organization can use hypothesis testing to determine whether a new treatment produces a significant improvement compared with an existing treatment.
   * H₀: There is no significant difference between the treatments.
   * H₁: There is a significant difference between the treatments.

Thus, hypothesis testing helps organizations make decisions based on statistical evidence rather than assumptions.
"""