# -*- coding: utf-8 -*-
"""Technical Lab Sheet 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pknq8W0R4RU8iXHE09m13FjN1ui1HdWZ

#### **Experiment No. 2**
#### **Experiment Name - Exploratory Data Analysis (EDA) on a Real-World Business Dataset using Python**

#### **Steps**

##### **NAME : Atul Krishna**
##### **COURSE : B.Tech CSE**
##### **SECTION - B**
##### **SUBJECT : Mastery in Data Analytics and Visualizations and Career Advancement**
##### **ROLL NO. : 14**
##### **CU ID : CU24250231**

#####**1. Select a real-world dataset such as the Netflix Titles Dataset, Superstore Sales Dataset, or IBM HR Employee Attrition Dataset.**

For this experiment, we use the Superstore Sales Dataset.

The dataset contains business-related information such as:

* Sales
* Profit
* Quantity
* Category
* Sub-Category
* Region
* Customer information
* Product information

#####**2. Import the required Python libraries (Pandas, NumPy, Matplotlib, and Seaborn) and load the cleaned dataset.**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files
uploaded = files.upload()  # select your Titanic CSV when prompted

import os
print(os.listdir())  # confirm the exact filename

print("Dataset loaded successfully!")

df = pd.read_csv("Superstore.csv", encoding="latin1")

print("Dataset loaded successfully!")
print("Shape of dataset:", df.shape)

"""#####**3. Explore the dataset by examining its dimensions, data types, column names, and summary statistics using functions such as info(), describe(), and value_counts().**"""

print("Column Names:")
print(df.columns)

print("\nDataset Information:")
df.info()

print("\nSummary Statistics:")
print(df.describe())

print("\nMissing Values:")
print(df.isnull().sum())

"""#####**4. Analyze the distribution of numerical features using histograms and density plots to understand central tendency and data spread.**"""

numerical_columns = df.select_dtypes(include=np.number).columns

df[numerical_columns].hist(
    figsize=(5, 4),
    bins=20
)

plt.tight_layout()
plt.show()

"""#####**5. Visualize categorical variables using bar charts and count plots to identify the most frequent categories.**"""

plt.figure(figsize=(5, 4))

sns.countplot(
    data=df,
    x="Category"
)

plt.title("Distribution of Product Categories")
plt.xlabel("Category")
plt.ylabel("Count")

plt.show()

"""#####**6. Generate a correlation matrix and heatmap to identify relationships between numerical variables and detect highly correlated features.**"""

numeric_df = df.select_dtypes(include=np.number)

correlation = numeric_df.corr()

plt.figure(figsize=(5, 4))

sns.heatmap(
    correlation,
    annot=True,
    cmap="coolwarm",
    fmt=".2f"
)

plt.title("Correlation Heatmap")

plt.show()

"""#####**7. Create box plots and scatter plots to identify outliers and study relationships between different variables.**"""

plt.figure(figsize=(5, 4))

sns.boxplot(
    data=df,
    y="Sales"
)

plt.title("Box Plot of Sales")
plt.ylabel("Sales")

plt.show()

plt.figure(figsize=(5, 4))

sns.scatterplot(
    data=df,
    x="Sales",
    y="Profit"
)

plt.title("Sales vs Profit")
plt.xlabel("Sales")
plt.ylabel("Profit")

plt.show()

"""#####**8. Perform univariate, bivariate, and multivariate analysis to uncover trends and business patterns within the dataset.**"""

print("Sales Statistics:")
print(df["Sales"].describe())

plt.figure(figsize=(5, 4))

sns.histplot(
    data=df,
    x="Sales",
    kde=True
)

plt.title("Sales Distribution")

plt.show()

plt.figure(figsize=(5, 4))

sns.scatterplot(
    data=df,
    x="Sales",
    y="Profit",
    hue="Category"
)

plt.title("Sales vs Profit by Category")

plt.show()

plt.figure(figsize=(5, 4))

sns.scatterplot(
    data=df,
    x="Sales",
    y="Profit",
    hue="Category",
    size="Quantity"
)

plt.title("Sales, Profit, Category and Quantity")

plt.show()

"""#####**9. Summarize key observations and identify factors that significantly influence the target variable or business objective.**"""

print("Average Sales:", df["Sales"].mean())
print("Average Profit:", df["Profit"].mean())
print("Maximum Sales:", df["Sales"].max())
print("Maximum Profit:", df["Profit"].max())

print("\nMost Common Category:")
print(df["Category"].mode()[0])

print("\nMost Common Region:")
print(df["Region"].mode()[0])

"""Key Observations

From the exploratory analysis, the following information can be obtained:

1. The average sales value represents the typical sales generated per transaction.
2. Average profit indicates the average profitability of transactions.
3. Maximum Sales identifies the highest-value transaction present in the dataset.
4. Maximum Profit identifies the most profitable transaction.
5. The most common category identifies the category with the greatest number of records.
6. The most common region shows which geographical region appears most frequently.
7. The scatter plot indicates that higher sales do not always guarantee higher profit.
8. The box plot reveals the presence of unusually high sales transactions.
9. The correlation heatmap identifies relationships between numerical business variables.
10. Category-wise visualization helps compare product performance.

#####**10. Prepare a concise report highlighting important findings and recommendations based on the exploratory analysis.**

#####**Findings**

EDA was successfully performed on the Superstore Sales Dataset.

The analysis showed the distribution of sales and other numerical variables, frequency of different product categories, relationships between numerical features, presence of potential outliers, and the relationship between Sales and Profit.

Univariate, bivariate, and multivariate analyses were performed to better understand different business patterns.

#####**Business Recommendations**

Based on the exploratory analysis:
* Product categories generating high profits should receive greater attention.
* High-sales but low-profit transactions should be investigated.
* Loss-generating transactions should be analyzed to determine whether discounts or other factors are responsible.
* High-performing regions and categories can be prioritized for business expansion.
* Unusual sales values should be examined before predictive modeling.
* Sales, Profit, Discount, Quantity and Category can be studied further for improving business decision-making.

Questions and Answers

Q1. What is Exploratory Data Analysis (EDA), and why is it performed before machine learning?

Answer - Exploratory Data Analysis or EDA is the process of examining and analyzing a dataset to understand its structure, distributions, relationships, patterns, and anomalies.

EDA is performed before machine learning because it helps identify:
* Missing values
* Outliers
* Skewed distributions
* Relationships between variables
* Incorrect data types
* Data quality problems

It allows analysts to properly understand and prepare the dataset before building predictive models.

Q2. Differentiate between univariate, bivariate, and multivariate analysis with suitable examples.

Answer -
| Analysis     | Meaning                             | Example                              |
| ------------ | ----------------------------------- | ------------------------------------ |
| Univariate   | Analysis of one variable            | Distribution of Sales                |
| Bivariate    | Analysis of two variables           | Sales vs Profit                      |
| Multivariate | Analysis of more than two variables | Sales, Profit, Category and Quantity |


Univariate analysis studies only one variable.

Example: Sales Distribution

Bivariate analysis studies the relationship between two variables.

Example: Sales vs Profit

Multivariate analysis studies several variables simultaneously.

Example: Sales + Profit + Category + Quantity

Q3. What insights can be obtained from a correlation heatmap?

Answer - A correlation heatmap shows the strength and direction of relationships between numerical variables.

It helps identify:
* Positive relationships
* Negative relationships
* Weak correlations
* Strong correlations
* Highly correlated features
* Potentially redundant variables

For example, it can help determine whether Sales has a positive or negative relationship with Profit, Quantity or Discount.

Q4. Explain the purpose of histograms, box plots, and scatter plots in EDA.

Answer -

Histogram - A histogram is used to study the distribution and frequency of numerical data.

It helps identify:
* Distribution
* Central tendency
* Spread
* Skewness

Box Plot -

A box plot displays:
* Median
* Quartiles
* Spread
* Potential outliers

It is particularly useful for identifying unusually high or low values.

Scatter Plot - A scatter plot is used to analyze the relationship between two numerical variables.

For example: Sales vs Profit

can show whether Profit generally increases with Sales.

Q5. How can EDA help identify data quality issues before analysis?

Answer - EDA can identify several data quality problems, including:
* Missing values
* Duplicate records
* Outliers
* Incorrect data types
* Unusual values
* Inconsistent categories
* Skewed distributions
* Invalid values

By identifying these problems before analysis, the dataset can be properly cleaned and prepared for further processing and predictive modeling.

Q6. Why is correlation important in predictive analytics? Can correlation imply causation?

Answer - Correlation is important because it measures the relationship between numerical variables.

It can help identify:
* Variables useful for prediction
* Strongly related features
* Redundant variables
* Potential predictors

However, correlation does not imply causation.

Two variables may be correlated because of another hidden variable or coincidence. Therefore, correlation alone cannot prove that one variable causes another.

Q7. Which visualization would you use to analyze categorical and numerical variables? Justify your choice.

Answer - For categorical variables, suitable visualizations include:
* Bar charts
* Count plots

For example, a count plot can show how many records belong to each Product Category.

For numerical variables, suitable visualizations include:
* Histograms
* Box plots
* Scatter plots

A histogram helps understand numerical distributions, a box plot identifies outliers, and a scatter plot studies relationships between numerical variables.

Q8. What business insights can be derived from the Superstore dataset through EDA?

Answer - The Superstore dataset can provide business insights such as:
* Which product categories have the highest sales
* Which categories generate the most profit
* Which regions contain the greatest number of transactions
* Relationship between Sales and Profit
* Identification of loss-generating transactions
* Identification of unusually large sales
* Distribution of orders across categories
* Relationship between quantity and sales
* Potential effect of other numerical variables on profitability

These insights can help management make better data-driven business decisions.

Q9. How does EDA contribute to feature selection and model building?

Answer - EDA helps determine which variables may be useful for predictive modeling.

Correlation analysis can identify highly related variables, while distribution analysis helps identify skewed features and box plots can reveal outliers.

EDA therefore helps in:
* Selecting useful features
* Detecting redundant features
* Understanding relationships
* Identifying outliers
* Detecting skewness
* Preparing variables for machine learning
* Improving model quality

Q10. What challenges might arise while performing EDA on large-scale real-world datasets?

Answer - Some common challenges include:
* Very large dataset size
* High memory consumption
* High computational requirements
* Missing or inconsistent data
* Large numbers of features
* Difficulty visualizing millions of records
* Outliers and noisy observations
* Complex relationships among variables
* Long processing times
* Difficulty interpreting large numbers of visualizations

Therefore, large datasets may require efficient data-processing techniques, sampling methods, scalable tools, and appropriate visualization strategies.
"""