# -*- coding: utf-8 -*-
"""Technical Lab Sheet 4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KJ-ATRgP88jVJ4eTOvEQpi8YhyKskALf

#### **Experiment No. 4**
#### **Experiment Name - Advanced Data Visualization using Matplotlib and Seaborn**

#### **Steps**

##### **NAME : Atul Krishna**
##### **COURSE : B.Tech CSE**
##### **SECTION - B**
##### **SUBJECT : Mastery in Data Analytics and Visualizations and Career Advancement**
##### **ROLL NO. : 14**
##### **CU ID : CU24250231**

**1. Select a real-world dataset such as the Superstore Sales Dataset, Netflix Dataset, COVID-19 Dataset, or World Happiness Report.**
"""

# Selecting a Real-World Dataset
from google.colab import files
uploaded = files.upload()

import os
print(os.listdir())

dataset_name = "Superstore Sales Dataset"

print("Selected Dataset:", dataset_name)
print("Dataset selected successfully!")

"""**2. Import the required libraries (Pandas, Matplotlib, and Seaborn) and load the cleaned dataset.**"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load the cleaned dataset
df = pd.read_csv("Superstore.csv")

print("Dataset loaded successfully.")

"""**3. Create bar charts to compare categorical variables such as sales by region, genre distribution, or product categories.**"""

# Calculate total sales for each region
region_sales = df.groupby("Region")["Sales"].sum().reset_index()

# Create the bar chart
plt.figure(figsize=(4, 3))

sns.barplot(
    data=region_sales,
    x="Region",
    y="Sales"
)

plt.title("Total Sales by Region")
plt.xlabel("Region")
plt.ylabel("Total Sales")
plt.tight_layout()
plt.show()

"""**4. Generate line charts to analyze trends over time, such as monthly sales, yearly movie releases, or daily COVID-19 cases.**"""

# Convert Order Date into datetime format
# dayfirst=True is used because the dates are in DD/MM/YYYY format
df["Order Date"] = pd.to_datetime(df["Order Date"], dayfirst=True)

# Calculate total sales for each month
monthly_sales = df.groupby(
    df["Order Date"].dt.to_period("M")
)["Sales"].sum()

# Convert the month values into strings for the x-axis
monthly_sales.index = monthly_sales.index.astype(str)

# Create the line chart
plt.figure(figsize=(10, 5))

plt.plot(
    monthly_sales.index,
    monthly_sales.values,
    marker="o"
)

# Add title and axis labels
plt.title("Monthly Sales Trend")
plt.xlabel("Month")
plt.ylabel("Total Sales")

# Rotate the month labels for better readability
plt.xticks(rotation=45)

# Display grid lines
plt.grid(True)

# Adjust the layout
plt.tight_layout()

# Display the chart
plt.show()

"""**5. Plot histograms to study the distribution of numerical variables such as sales, ratings, or customer age.**

"""

# Create a histogram to study the distribution of Sales
plt.figure(figsize=(6, 5))

sns.histplot(
    data=df,
    x="Sales",
    bins=30,
    kde=True
)

plt.title("Distribution of Sales")
plt.xlabel("Sales")
plt.ylabel("Frequency")
plt.tight_layout()
plt.show()

"""**6. Create box plots to identify outliers and compare distributions across different categories.**

"""

# Create a box plot to compare Sales across different Regions
plt.figure(figsize=(6, 5))

sns.boxplot(
    data=df,
    x="Region",
    y="Sales"
)

plt.title("Sales Distribution by Region")
plt.xlabel("Region")
plt.ylabel("Sales")
plt.tight_layout()
plt.show()

"""**7. Generate scatter plots to analyze relationships between two numerical variables, such as advertising expenditure vs. sales or budget vs. revenue.**"""

# Create a scatter plot to analyze the relationship between Postal Code and Sales
plt.figure(figsize=(9, 4))

sns.scatterplot(
    data=df,
    x="Postal Code",
    y="Sales"
)

plt.title("Relationship Between Postal Code and Sales")
plt.xlabel("Postal Code")
plt.ylabel("Sales")
plt.tight_layout()
plt.show()

"""**8. Create a correlation heatmap using Seaborn to visualize relationships among numerical features.**"""

# Select only numerical columns from the dataset
numeric_data = df.select_dtypes(include="number")

# Calculate the correlation matrix
correlation_matrix = numeric_data.corr()

# Create the correlation heatmap
plt.figure(figsize=(5, 4))

sns.heatmap(
    correlation_matrix,
    annot=True,
    cmap="coolwarm",
    fmt=".2f"
)

plt.title("Correlation Heatmap of Numerical Features")
plt.tight_layout()
plt.show()

"""**9. Customize the visualizations by adding titles, axis labels, legends, annotations, and appropriate color palettes to improve readability.**

"""

# Calculate total sales for each region
region_sales = df.groupby("Region")["Sales"].sum().reset_index()

# Create the bar chart
plt.figure(figsize=(7, 4))

ax = sns.barplot(
    data=region_sales,
    x="Region",
    y="Sales",
    hue="Region",
    palette="viridis"
)

# Add title and axis labels
plt.title("Total Sales by Region")
plt.xlabel("Region")
plt.ylabel("Total Sales")

# Add annotations
for i, value in enumerate(region_sales["Sales"]):
    ax.text(i, value, f"{value:.0f}", ha="center", va="bottom")

plt.legend(title="Region")
plt.tight_layout()
plt.show()

"""**10. Interpret each visualization and prepare a summary highlighting key business insights obtained from the graphical analysis.**

### Interpretation of Visualizations and Business Insights

1. **Bar Chart – Sales by Region:**
   The bar chart helps compare the total sales generated by different regions. It shows which regions are performing better and which regions have comparatively lower sales. This information can help the business identify strong-performing regions and focus on improving sales in weaker regions.

2. **Line Chart – Monthly Sales Trend:**
   The line chart shows how sales change over time on a monthly basis. Peaks in the chart represent months with higher sales, while lower points represent months with lower sales. This helps the business identify sales trends and plan inventory, marketing campaigns, and resources accordingly.

3. **Histogram – Distribution of Sales:**
   The histogram shows how frequently different sales values occur. It helps understand the distribution of sales and whether most orders have low, medium, or high sales values. It can also indicate whether the data is skewed or contains unusual values.

4. **Box Plot – Sales by Region:**
   The box plot compares the distribution of sales across different regions. It shows the median, spread, and potential outliers in sales. Regions with greater variation may require further investigation to understand the reasons for differences in order values.

5. **Scatter Plot – Relationship Between Numerical Variables:**
   The scatter plot displays individual data points for two numerical variables and helps identify patterns or relationships between them. A clear upward or downward pattern may indicate a relationship, while widely scattered points suggest a weak relationship.

6. **Correlation Heatmap:**
   The correlation heatmap shows the strength and direction of relationships between numerical features. Values close to +1 indicate a strong positive relationship, values close to -1 indicate a strong negative relationship, and values close to 0 indicate a weak linear relationship. It can help identify related features and support feature selection in machine learning.

### Overall Business Insights

The visual analysis makes it easier to understand regional sales performance, monthly sales trends, sales distribution, variations, and relationships between numerical variables. These insights can support business decisions related to sales planning, inventory management, marketing strategies, regional performance improvement, and future predictive analysis.

Overall, data visualization converts complex numerical data into an easy-to-understand graphical form and helps organizations make better data-driven business decisions.

**Questions and Answers**
1. Why is data visualization considered an essential component of data analytics?

Answer: Data visualization is an essential component of data analytics because it represents complex data in the form of graphs, charts, and plots, making it easier to understand. It helps analysts identify trends, patterns, relationships, distributions, and outliers that may not be easily visible in raw numerical data.

Visualization also helps in communicating analytical results clearly to decision-makers. For example, a line chart can quickly show monthly sales trends, while a bar chart can compare sales across different regions. Therefore, data visualization supports faster understanding and better data-driven decision-making.

2. Differentiate between Matplotlib and Seaborn. Which library is more suitable for statistical visualizations and why?

Answer: Matplotlib and Seaborn are both Python libraries used for data visualization, but they differ in their features and ease of use.

| Matplotlib                                      | Seaborn                                                |
| ----------------------------------------------- | ------------------------------------------------------ |
| General-purpose visualization library           | Statistical data visualization library                 |
| Provides detailed control over plots            | Provides simpler and more attractive statistical plots |
| Requires more code for advanced visualizations  | Requires comparatively less code                       |
| Suitable for basic and highly customized charts | Suitable for statistical analysis and visualization    |
| Works mainly with Matplotlib objects            | Built on top of Matplotlib                             |

Seaborn is more suitable for statistical visualizations because it provides built-in functions for creating plots such as box plots, heatmaps, distribution plots, and regression plots. It also works easily with Pandas DataFrames.

3. Which type of chart would you choose to compare sales across different regions? Justify your answer.

Answer: I would choose a bar chart to compare sales across different regions.

A bar chart is suitable because Region is a categorical variable and Sales is a numerical variable. Each bar represents the total sales of a particular region, making it easy to compare the performance of different regions.

For example, a business can quickly identify its highest and lowest sales-performing regions using a bar chart.

4. What information can be obtained from a histogram and a box plot?

Answer: A histogram shows the distribution of a numerical variable by dividing the data into intervals or bins. It helps identify:
* Frequency of values
* Distribution of data
* Common value ranges
* Skewness of the data
* General shape of the distribution

A box plot provides information about the statistical distribution of data. It shows:
* Minimum and maximum values
* Median
* First and third quartiles
* Interquartile range (IQR)
* Potential outliers

Therefore, a histogram is mainly useful for understanding the overall distribution, while a box plot is particularly useful for comparing distributions and detecting outliers.

5. Explain the purpose of a scatter plot. How does it help in identifying relationships between variables?

Answer: A scatter plot is used to visualize the relationship between two numerical variables. Each point on the graph represents one observation, with one variable plotted on the X-axis and the other on the Y-axis.

It helps identify whether the variables have a:
* Positive relationship
* Negative relationship
* Weak relationship
* No clear relationship

For example, if points generally move upward from left to right, it may indicate a positive relationship between the variables. Scatter plots can also help identify clusters and unusual observations (outliers).

However, correlation or association between two variables does not by itself prove that one variable causes the other.

6. What is a correlation heatmap? How can it assist in feature selection for machine learning?

Answer: A correlation heatmap is a graphical representation of the correlation matrix between numerical variables. It uses different colors to represent the strength and direction of relationships between variables.

Correlation values generally range from -1 to +1:
* +1 → Strong positive correlation
* 0 → No linear correlation
* -1 → Strong negative correlation

In machine learning, a correlation heatmap can help identify highly correlated features. If two features are highly correlated, they may contain similar information. Removing redundant features can sometimes reduce multicollinearity and simplify the model.

However, correlation should not be the only method used for feature selection because it mainly measures linear relationships.

7. Why is chart customization (titles, labels, legends, colors) important in data visualization?

Answer: Chart customization is important because it improves the readability, clarity, and interpretation of a visualization.
* Titles explain what the chart represents.
* Axis labels identify the variables being displayed.
* Legends explain different data series or categories.
* Colors help distinguish between different groups.
* Annotations can display important values directly on the chart.

Proper customization makes the visualization easier to understand and helps communicate insights effectively without confusing the viewer.

8. What factors should be considered while selecting an appropriate visualization for a dataset?

Answer: The following factors should be considered when selecting a suitable visualization:
1. Type of data – categorical, numerical, or time-series.
2. Purpose of analysis – comparison, distribution, trend, relationship, or composition.
3. Number of variables – one variable, two variables, or multiple variables.
4. Size of the dataset – large datasets may require simpler or aggregated visualizations.
5. Audience – the visualization should be understandable to the intended audience.
6. Need to identify outliers or patterns – box plots and scatter plots can be useful for this purpose.
7. Readability – the chart should not contain unnecessary elements.

For example, a bar chart is suitable for categorical comparisons, a line chart for trends over time, and a scatter plot for relationships between numerical variables.

9. How can misleading visualizations affect business decision-making? Give a real-world example.

Answer: Misleading visualizations can cause businesses to misinterpret data and make incorrect decisions. This can happen due to inappropriate scales, truncated axes, incorrect chart types, selective data presentation, or misleading colors.

For example, suppose a company's sales increased from ₹100 lakh to ₹105 lakh. If a bar chart starts its Y-axis at ₹99 lakh instead of zero, the increase may visually appear much larger than it actually is. Management might incorrectly conclude that sales have grown significantly and make unnecessary investment decisions.

Therefore, charts should use appropriate scales, accurate labels, complete context, and suitable visualization techniques to avoid misleading conclusions.

10. Explain how data visualization supports storytelling and business intelligence in organizations.

Answer: Data visualization supports data storytelling by converting raw data and analytical results into visual information that is easier to understand. It helps organizations communicate important findings through charts, graphs, dashboards, and reports.

In Business Intelligence (BI), visualization helps decision-makers monitor important business metrics such as:
* Sales and revenue
* Customer performance
* Regional performance
* Product performance
* Market trends
* Operational performance

For example, a business dashboard can show monthly sales trends, top-performing products, and regional sales using different charts. Managers can quickly identify problems and opportunities and take appropriate actions.

Therefore, data visualization connects data analysis with business decision-making and helps organizations make faster and more informed decisions.
"""